In [2]:
from connec_functions import execute_to_df, generate_sparql
import pandas as pd

- (Because of different analysis method, using the linked data, results can differ a bit.  
- Linked data makes it faster/easier to analyse a larger amount of data)

### Publications in the LifeWatch special collections:

In [7]:
spcol_pubs = execute_to_df("0_spcol_pubs.sparql")
spcol_pubs

,collection,title,publication
0,https://marineinfo.org/id/collection/919,EurOBIS ackn,https://marineinfo.org/id/publication/244397
1,https://marineinfo.org/id/collection/919,European Oceanographic Biogeographic Informati...,https://marineinfo.org/id/publication/244397
2,https://marineinfo.org/id/collection/945,EUROBIS ackn - indirect,https://marineinfo.org/id/publication/244397
3,https://marineinfo.org/id/collection/945,EUROBIS ackn - indirect use,https://marineinfo.org/id/publication/244397
4,https://marineinfo.org/id/collection/923,Lifewatch ackn,https://marineinfo.org/id/publication/244397
...,...,...,...
49845,https://marineinfo.org/id/collection/947,WoRMS ackn - direct,https://marineinfo.org/id/publication/359937
49846,https://marineinfo.org/id/collection/947,WoRMS ackn - direct reference,https://marineinfo.org/id/publication/359937
49847,https://marineinfo.org/id/collection/941,LifeWatch Species Information Backbone,https://marineinfo.org/id/publication/391955
49848,https://marineinfo.org/id/collection/793,Marine Regions ackn,https://marineinfo.org/id/publication/391955
49849,https://marineinfo.org/id/collection/793,Marine Regions acknowledged,https://marineinfo.org/id/publication/391955

In [8]:
#LifeWatch special collections with number of publications
lw_spcols = spcol_pubs.groupby('collection').nunique()
lw_spcols

                                          title  publication
collection
https://marineinfo.org/id/collection/793      2          841
https://marineinfo.org/id/collection/896      1          337
https://marineinfo.org/id/collection/897      1           13
https://marineinfo.org/id/collection/915      2         8660
https://marineinfo.org/id/collection/919      2          357
https://marineinfo.org/id/collection/923      2          970
https://marineinfo.org/id/collection/941      1         9740
https://marineinfo.org/id/collection/942      2           94
https://marineinfo.org/id/collection/944      2           27
https://marineinfo.org/id/collection/945      2          260
https://marineinfo.org/id/collection/947      2         8651
https://marineinfo.org/id/collection/986      1           23
https://marineinfo.org/id/collection/987      1           17

In [11]:
test = spcol_pubs[ spcol_pubs['collection'] == 'https://marineinfo.org/id/collection/915']
test.groupby('publication').nunique()

                                              collection  title
publication
https://marineinfo.org/id/publication/100077           1      2
https://marineinfo.org/id/publication/100293           1      2
https://marineinfo.org/id/publication/100297           1      2
https://marineinfo.org/id/publication/100354           1      2
https://marineinfo.org/id/publication/100404           1      2
...                                                  ...    ...
https://marineinfo.org/id/publication/98292            1      2
https://marineinfo.org/id/publication/99798            1      2
https://marineinfo.org/id/publication/99962            1      2
https://marineinfo.org/id/publication/99971            1      2
https://marineinfo.org/id/publication/99972            1      2

[8660 rows x 2 columns]

In [12]:
# Number of LifeWatch publications --> many occur in multiple collections 
lw_pubs = spcol_pubs.groupby('publication').nunique()

print(f'There are {lw_pubs.shape[0]} publications in the LW special collections.')
lw_pubs

There are 10602 publications in the LW special collections.

                                              collection  title
publication
https://marineinfo.org/id/publication/100077           3      5
https://marineinfo.org/id/publication/100293           3      5
https://marineinfo.org/id/publication/100295           3      5
https://marineinfo.org/id/publication/100297           5      9
https://marineinfo.org/id/publication/100343           3      5
...                                                  ...    ...
https://marineinfo.org/id/publication/98292            3      5
https://marineinfo.org/id/publication/99798            3      5
https://marineinfo.org/id/publication/99962            3      5
https://marineinfo.org/id/publication/99971            3      5
https://marineinfo.org/id/publication/99972            3      5

[10602 rows x 2 columns]